# Generated by Django 3.1.3 on 2020-11-29 13:42

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201129_1907'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthorpage',
            name='person',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_authors', to='home.people'),
        ),
    ]
