# Generated by Django 3.1.4 on 2020-12-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201202_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='isbn',
        ),
        migrations.AddField(
            model_name='productpage',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='List Price'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='qty_in_stock',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8, verbose_name='Qty in Stock'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='uid_or_isbn',
            field=models.CharField(default='xyz', max_length=13, unique=True, verbose_name='UID or ISBN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Product Home', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub title'),
        ),
    ]
