# Generated by Django 3.1.4 on 2020-12-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('product', '0004_auto_20201219_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='curr',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='price',
        ),
        migrations.AddField(
            model_name='productpage',
            name='curr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='currency.currency'),
        ),
    ]
