# Generated by Django 3.1.4 on 2020-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201219_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='active',
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='imprint',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Publisher Imprint'),
        ),
    ]
