# Generated by Django 3.1.4 on 2020-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201219_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Product Intro', null=True, verbose_name='Introduction'),
        ),
    ]
