# Generated by Django 3.1.4 on 2020-12-19 14:10

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201219_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='linked_products',
            field=modelcluster.fields.ParentalManyToManyField(to='product.ProductPage'),
        ),
    ]
