# Generated by Django 3.1.4 on 2020-12-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201219_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='related_titles',
        ),
    ]
