# Generated by Django 3.1.4 on 2020-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201219_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='linked_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_linked_products', to='product.ProductPage'),
        ),
    ]
