# Generated by Django 3.1.4 on 2020-12-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201219_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='linked_products',
        ),
    ]
