# Generated by Django 3.1.4 on 2020-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productpage_linked_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpage',
            old_name='pages',
            new_name='book_pages',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='subjects',
        ),
    ]
