# Generated by Django 3.1.3 on 2020-11-29 13:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prize', '0001_initial'),
        ('home', '0001_initial'),
        ('product', '0001_initial'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizewinner',
            name='book',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_prizes', to='product.bookpage'),
        ),
        migrations.AddField(
            model_name='prizewinner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_winners', to='prize.prizepage'),
        ),
        migrations.AddField(
            model_name='prizewinner',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='home.people'),
        ),
        migrations.AddField(
            model_name='prizepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='prizepage',
            name='linked_products',
            field=models.ManyToManyField(to='product.ProductPage'),
        ),
        migrations.AddField(
            model_name='prizepage',
            name='prize_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='prize.TaggedPrize', to='prize.PrizeTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='prizeindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
