# Generated by Django 3.1.4 on 2020-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0003_auto_20201202_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Updated on'),
        ),
    ]
