# Generated by Django 3.1.3 on 2020-11-29 13:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('home', '0001_initial'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='home.people'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.TaggedBlog', to='blog.BlogTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
