# Generated by Django 3.1.3 on 2020-11-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('blog', '0002_auto_20201129_1904'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='linked_products',
            field=models.ManyToManyField(to='product.ProductPage'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
