# Generated by Django 3.1.3 on 2020-11-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state_name'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterField(
            model_name='state',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='home.country'),
        ),
    ]
